export type Product = {
  id: string;
  name: string;
  tagline: string;
  source: "Product Hunt" | "WhatLaunched";
  sourceUrl: string;
  website: string;
  launchedAt: string;
  category: string;
  score: number;
  pricing: string;
  pricingModel: string;
  targetUsers: string[];
  positioning: string;
  businessModel: string;
  competitors: string[];
  opportunities: string[];
  risks: string[];
  signals: string[];
  confidence: number;
  verifiedAt: string;
  factStatus: "已核验" | "待复核";
  analysisNote: string;
};
